name: build-resume

on:
  push:
    branches: [ main ]
    tags:        
      - '*'  
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mikefarah/yq@master
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
          check-latest: true
      - name: build-resume
        run: |
          yq -o=json eval resume.yaml > resume.json
          npm install
          npm start
      - uses: actions/upload-artifact@v3
        with:
          name: resume.pdf
          path: resume.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            resume.pdf
