name: build-resume

on:
  push:
    branches: [ main ]
    tags:        
      - '*'  
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: fonts-roboto
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: resume.typ
      - uses: actions/upload-artifact@v4
        with:
          name: resume.pdf
          path: resume.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            resume.pdf
