name: release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: mikefarah/yq@master
      
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          check-latest: true
        
      - name: build-resume
        run: |
          npm install resumed  jsonresume-theme-kwan
          yq -o=json eval resume.yaml > resume.json
          resumed export --theme kwan
      
      - name: debug
        run: |
          pwd
          ls -la
          tree
          
      - name: convert-resume
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: resume.html
          outputFile: resume.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
          
      - uses: actions/upload-artifact@v3
        with:
          name: resume.pdf
          path: resume.pdf
